[ESP32S3_E22]
extends = esp32_base
platform = espressif32
board = ESP32-S3-WROOM-1-N16R8
board_build.variant = esp32s3_e22
board_upload.flash_size = 16MB
board_build.flash_size = 16MB
board_build.partitions = partitions_16MB_s3_opi.csv
board_build.mcu = esp32s3
board_build.f_cpu = 240000000L
board_build.psram_type = opi
board_build.usb_mode = cdc
board_build.has_psram = yes

build_flags =
  ${esp32_base.build_flags}
  -DBOARD_HAS_PSRAM
  -DARDUINO_USB_MODE=0
  -DARDUINO_USB_CDC_ON_BOOT=0
  -DARDUINO_USB_DFU_ON_BOOT=0
  -D PIN_VBAT_READ=1
  -D PIN_USER_BTN=0
  -D P_LORA_DIO_1=42
  -D P_LORA_NSS=14
  -D P_LORA_RESET=40
  -D P_LORA_BUSY=41
  -D P_LORA_SCLK=15
  -D P_LORA_MOSI=38
  -D P_LORA_MISO=39
  -D SX126X_TXEN=16
  -D SX126X_RXEN=17
  -D PIN_BOARD_SDA=8
  -D PIN_BOARD_SCL=18
  -D SX126X_DIO2_AS_RF_SWITCH=true
  -D SX126X_DIO3_TCXO_VOLTAGE=1.8
  -D PIN_GPS_RX=13
  -D PIN_GPS_TX=12
  -D SX126X_CURRENT_LIMIT=140
  -I variants/esp32s3_e22
build_src_filter =
  ${esp32_base.build_src_filter}
  +<../variants/esp32s3_e22>
lib_deps =
  ${esp32_base.lib_deps}
  ;adafruit/Adafruit SH110X @ ^2.1.14
  adafruit/Adafruit SSD1306 @ ^2.5.13

; ----------------- ESP32S3 E22 Derived Environments -----------------

[env:ESP32S3_E22_sx1262_repeater]
extends = ESP32S3_E22
build_flags =
  ${ESP32S3_E22.build_flags}
  -D RADIO_CLASS=CustomSX1262
  -D WRAPPER_CLASS=CustomSX1262Wrapper
  -D LORA_TX_POWER=22
  -D ADVERT_NAME='"S3-E22 Repeater"'
  -D ADMIN_PASSWORD='"password"'
  -D MAX_NEIGHBOURS=50
  -D DISPLAY_CLASS=SSD1306Display
build_src_filter =
  ${ESP32S3_E22.build_src_filter}
  +<../examples/simple_repeater>
  +<helpers/ui/SSD1306Display.cpp>
lib_deps =
  ${ESP32S3_E22.lib_deps}
  ${esp32_ota.lib_deps}

[env:ESP32S3_E22_sx1262_repeater_bridge_espnow]
extends = ESP32S3_E22
build_src_filter =
  ${ESP32S3_E22.build_src_filter}
  +<helpers/bridges/ESPNowBridge.cpp>
  +<../examples/simple_repeater/*.cpp>
build_flags =
  ${ESP32S3_E22.build_flags}
  -D RADIO_CLASS=CustomSX1262
  -D WRAPPER_CLASS=CustomSX1262Wrapper
  -D WITH_ESPNOW_BRIDGE=1
  -D LORA_TX_POWER=22
  -D MAX_NEIGHBOURS=50
lib_deps =
  ${ESP32S3_E22.lib_deps}
  ${esp32_ota.lib_deps}

[env:ESP32S3_E22_sx1262_room_server]
extends = ESP32S3_E22
build_flags =
  ${ESP32S3_E22.build_flags}
  -D RADIO_CLASS=CustomSX1262
  -D WRAPPER_CLASS=CustomSX1262Wrapper
  -D LORA_TX_POWER=22
  -D ADVERT_NAME='"S3-E22 Room"'
  -D ROOM_PASSWORD='"hello"'
build_src_filter =
  ${ESP32S3_E22.build_src_filter}
  +<../examples/simple_room_server/*.cpp>
  +<helpers/ui/SSD1306Display.cpp>
lib_deps =
  ${ESP32S3_E22.lib_deps}
  ${esp32_ota.lib_deps}

[env:ESP32S3_E22_sx1262_companion_radio_usb]
extends = ESP32S3_E22
build_src_filter =
  ${ESP32S3_E22.build_src_filter}
  +<../examples/companion_radio/*.cpp>
  +<helpers/ui/SSD1306Display.cpp>
build_flags =
  ${ESP32S3_E22.build_flags}
  -D RADIO_CLASS=CustomSX1262
  -D WRAPPER_CLASS=CustomSX1262Wrapper
  -D MAX_CONTACTS=100
  -D MAX_GROUP_CHANNELS=40
  -D LORA_TX_POWER=22
lib_deps =
  ${ESP32S3_E22.lib_deps}
  densaugeo/base64 @ ~1.4.0

[env:ESP32S3_E22_sx1262_companion_radio_ble]
extends = ESP32S3_E22
build_src_filter =
  ${ESP32S3_E22.build_src_filter}
  +<../examples/companion_radio/*.cpp>
  +<helpers/ui/MomentaryButton.cpp>
  +<helpers/ui/SSD1306Display.cpp>
build_flags =
  ${ESP32S3_E22.build_flags}
  -D RADIO_CLASS=CustomSX1262
  -D WRAPPER_CLASS=CustomSX1262Wrapper
  -D MAX_CONTACTS=100
  -D MAX_GROUP_CHANNELS=40
  -D BLE_PIN_CODE=123456
  -D BLE_DEBUG_LOGGING=1
  -D OFFLINE_QUEUE_SIZE=256
  -D LORA_TX_POWER=22
lib_deps =
  ${ESP32S3_E22.lib_deps}
  densaugeo/base64 @ ~1.4.0

[env:ESP32S3_E22_sx1262_terminal_chat]
extends = ESP32S3_E22
build_src_filter =
  ${ESP32S3_E22.build_src_filter}
  +<../examples/simple_secure_chat/main.cpp>
  +<helpers/ui/SSD1306Display.cpp>
build_flags =
  ${ESP32S3_E22.build_flags}
  -D RADIO_CLASS=CustomSX1262
  -D WRAPPER_CLASS=CustomSX1262Wrapper
  -D MAX_CONTACTS=100
  -D LORA_TX_POWER=22
lib_deps =
  ${ESP32S3_E22.lib_deps}
  densaugeo/base64 @ ~1.4.0
